
@echo off

:: BatchGotAdmin
:-------------------------------------
REM  --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"=""
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
powershell.exe -executionpolicy bypass -NoExit -encodedCommand dwBoAGkAbABlACgAJAB0AHIAdQBlACkAIAB7AA0ACgAgACAAIAAgACMAIABDAGgAZQBjAGsAIABpAGYAIABRAEIAVwBlAGIAQwBvAG4AbgBlAGMAdABvAHIAIABwAHIAbwBjAGUAcwBzACAAaQBzACAAcgB1AG4AbgBpAG4AZwANAAoAIAAgACAAIAAkAHEAYgB3AGUAYgBjAG8AbgBuAGUAYwB0AG8AcgAgAD0AIABHAGUAdAAtAFAAcgBvAGMAZQBzAHMAIAAiAFEAQgBXAGUAYgBDAG8AbgBuAGUAYwB0AG8AcgAiACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlAA0ACgAgACAAIAAgAGkAZgAgACgAIQAkAHEAYgB3AGUAYgBjAG8AbgBuAGUAYwB0AG8AcgApACAAewANAAoAIAAgACAAIAAgACAAIAAgACMAIABTAHQAYQByAHQAIABPAHUAdABsAG8AbwBrACAAaQBmACAAaQB0ACAAaQBzACAAbgBvAHQAIAByAHUAbgBuAGkAbgBnAA0ACgAgACAAIAAgACAAIAAgACAAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgACIAQwA6AFwAUAByAG8AZwByAGEAbQAgAEYAaQBsAGUAcwAgACgAeAA4ADYAKQBcAEMAbwBtAG0AbwBuACAARgBpAGwAZQBzAFwASQBuAHQAdQBpAHQAXABRAHUAaQBjAGsAQgBvAG8AawBzAFwAUQBCAFcAZQBiAEMAbwBuAG4AZQBjAHQAbwByAFwAUQBCAFcAZQBiAEMAbwBuAG4AZQBjAHQAbwByAC4AZQB4AGUAIgANAAoAIAAgACAAIAB9AA0ACgAgACAAIAAgACMAIABDAGgAZQBjAGsAIABpAGYAIABRAEIAIABwAHIAbwBjAGUAcwBzACAAaQBzACAAcgB1AG4AbgBpAG4AZwANAAoAIAAgACAAIAAkAHEAYgAgAD0AIABHAGUAdAAtAFAAcgBvAGMAZQBzAHMAIAAiAFEAQgBXADMAMgAiACAALQBFAHIAcgBvAHIAQQBjAHQAaQBvAG4AIABTAGkAbABlAG4AdABsAHkAQwBvAG4AdABpAG4AdQBlAA0ACgAgACAAIAAgAGkAZgAgACgAIQAkAHEAYgApACAAewANAAoAIAAgACAAIAAgACAAIAAgACMAIABTAHQAYQByAHQAIABXAG8AcgBkACAAaQBmACAAaQB0ACAAaQBzACAAbgBvAHQAIAByAHUAbgBuAGkAbgBnAA0ACgAgACAAIAAgACAAIAAgACAAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgACIAIgBDADoAXABQAHIAbwBnAHIAYQBtACAARgBpAGwAZQBzACAAKAB4ADgANgApAFwASQBuAHQAdQBpAHQAXABRAHUAaQBjAGsAQgBvAG8AawBzACAARQBuAHQAZQByAHAAcgBpAHMAZQAgAFMAbwBsAHUAdABpAG8AbgBzACAAMgAxAC4AMABcAFEAQgBXADMAMgBFAG4AdABlAHIAcAByAGkAcwBlAFcAaABvAGwAZQBzAGEAbABlAC4AZQB4AGUAIgAiAA0ACgAgACAAIAAgAH0ADQAKACAAIAAgACAAIwAgAFcAYQBpAHQAIABmAG8AcgAgADMAMAAgAG0AaQBuAHUAdABlAHMADQAKACAAIAAgACAAUwB0AGEAcgB0AC0AUwBsAGUAZQBwACAALQBTAGUAYwBvAG4AZABzACAAKAAzADAAIAAqACAANgAwACkADQAKAH0A
