
@echo off

:: BatchGotAdmin
:-------------------------------------
REM  --> Check for permissions
>nul 2>&1 "%SYSTEMROOT%\system32\cacls.exe" "%SYSTEMROOT%\system32\config\system"

REM --> If error flag set, we do not have admin.
if '%errorlevel%' NEQ '0' (
    echo Requesting administrative privileges...
    goto UACPrompt
) else ( goto gotAdmin )

:UACPrompt
    echo Set UAC = CreateObject^("Shell.Application"^) > "%temp%\getadmin.vbs"
    set params = %*:"=""
    echo UAC.ShellExecute "cmd.exe", "/c %~s0 %params%", "", "runas", 1 >> "%temp%\getadmin.vbs"

    "%temp%\getadmin.vbs"
    del "%temp%\getadmin.vbs"
    exit /B

:gotAdmin
    pushd "%CD%"
    CD /D "%~dp0"
powershell.exe -executionpolicy bypass -NoExit -encodedCommand ZgB1AG4AYwB0AGkAbwBuACAATABlAG4AbwB2AG8AVQBwAGQAYQB0AGUAcwANAAoAewANAAoACQBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgAqACoAKgAqACoAIABVAHAAZABhAHQAZQAgAEQAcgBpAHYAZQByAHMAIAAqACoAKgAqACoAIgAgAC0ARgBvAHIAZQBnAHIAbwB1AG4AZABDAG8AbABvAHIAIABHAHIAZQBlAG4ADQAKAAkAUwB0AGEAcgB0AC0AUAByAG8AYwBlAHMAcwAgAGMAbQBkACAALQBBAHIAZwB1AG0AZQBuAHQATABpAHMAdAAgACIALwBjACAAUAByAGUAcwBlAG4AdABhAHQAaQBvAG4AUwBlAHQAdABpAG4AZwBzACAALwBzAHQAYQByAHQAIgAgAC0ATgBvAE4AZQB3AFcAaQBuAGQAbwB3AA0ACgAJAFMAZQB0AC0ASQB0AGUAbQBQAHIAbwBwAGUAcgB0AHkAIAAtAFAAYQB0AGgAIABSAEUARwBJAFMAVABSAFkAOgA6AEgASwBFAFkAXwBMAE8AQwBBAEwAXwBNAEEAQwBIAEkATgBFAFwAUwBvAGYAdAB3AGEAcgBlAFwATQBpAGMAcgBvAHMAbwBmAHQAXABXAGkAbgBkAG8AdwBzAFwAQwB1AHIAcgBlAG4AdABWAGUAcgBzAGkAbwBuAFwAUABvAGwAaQBjAGkAZQBzAFwAUwB5AHMAdABlAG0AIAAtAE4AYQBtAGUAIABDAG8AbgBzAGUAbgB0AFAAcgBvAG0AcAB0AEIAZQBoAGEAdgBpAG8AcgBBAGQAbQBpAG4AIAAtAFYAYQBsAHUAZQAgADAADQAKAAkASQBuAHMAdABhAGwAbAAtAFAAYQBjAGsAYQBnAGUAUAByAG8AdgBpAGQAZQByACAALQBOAGEAbQBlACAATgB1AEcAZQB0ACAALQBGAG8AcgBjAGUADQAKAAkASQBuAHMAdABhAGwAbAAtAE0AbwBkAHUAbABlACAALQBOAGEAbQBlACAAJwBMAFMAVQBDAGwAaQBlAG4AdAAnACAALQBGAG8AcgBjAGUADQAKAAkAJAB1AHAAZABhAHQAZQBzACAAPQAgAEcAZQB0AC0ATABTAFUAcABkAGEAdABlAA0ACgAJACQAdQBwAGQAYQB0AGUAcwAgAHwAIABJAG4AcwB0AGEAbABsAC0ATABTAFUAcABkAGEAdABlACAALQBWAGUAcgBiAG8AcwBlAA0ACgAJAA0ACgB9AA0ACgANAAoATABlAG4AbwB2AG8AVQBwAGQAYQB0AGUAcwA=
